
POST  http://localhost:5056/api/Users
Content-Type: application/json

{
  "email": "jane.doe@example.com",
  "firstName": "Jane",
  "lastName": "Doe",
  "password": "1q2w#E$R",
  "roleIds": [1, 2]
}

###
GET   http://localhost:5056/api/Users
Content-Type: application/json